version: '3.8'

services:
  # Flask API Backend
  kiosk-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: kiosk-452-backend
    ports:
      - "8000:8000"
    volumes:
      - ../kiosk-backyard:/app/kiosk-backyard
      - ../sensors:/app/sensors
      - ../voice:/app/voice
      - ../config:/app/config
      - ../assets:/app/assets
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    networks:
      - kiosk-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend with nginx
  kiosk-frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: kiosk-452-frontend
    ports:
      - "3000:80"
    volumes:
      - ../kiosk/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - kiosk-backend
    restart: unless-stopped
    networks:
      - kiosk-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Chromium Kiosk Display
  kiosk-display:
    build:
      context: .
      dockerfile: Dockerfile.display
    container_name: kiosk-452-display
    ports:
      - "5900:5900"  # VNC port
    volumes:
      - ../assets:/app/assets
    environment:
      - DISPLAY=:0
      - VNC_PASSWORD=raspberry
      - KIOSK_URL=http://kiosk-frontend
    depends_on:
      - kiosk-frontend
      - kiosk-backend
    restart: unless-stopped
    networks:
      - kiosk-network

networks:
  kiosk-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
