version: '3.8'

services:
  # VOICEVOX Engine for voice synthesis
  voicevox-engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: kiosk-452-voicevox
    ports:
      - "50021:50021"
    networks:
      - kiosk-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50021/version"]  # より軽量なエンドポイント
      interval: 30s
      timeout: 10s
      retries: 10  # リトライ回数を増加（5→10）
      start_period: 60s  # 初回ヘルスチェックまでの猶予時間を追加
    restart: unless-stopped

  # Flask API Backend
  kiosk-backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: kiosk-452-backend
    ports:
      - "8000:8000"
    volumes:
      - ../kiosk-backyard:/app/kiosk-backyard
      - ../sensors:/app/sensors
      - ../voice:/app/voice
      - ../config:/app/config
      - ../assets:/app/assets
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - VOICEVOX_URL=http://voicevox-engine:50021
      - OLLAMA_URL=http://ollama:11434
    restart: unless-stopped
    networks:
      - kiosk-network
    # depends_on:
    #   voicevox-engine:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend with nginx
  kiosk-frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: kiosk-452-frontend
    ports:
      - "3000:80"
    volumes:
      - ../kiosk/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - kiosk-backend
    restart: unless-stopped
    networks:
      - kiosk-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ollama for LLM text generation
  ollama:
    image: ollama/ollama:latest
    container_name: kiosk-452-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=5m
    networks:
      - kiosk-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/version"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  # Chromium Kiosk Display
  kiosk-display:
    build:
      context: .
      dockerfile: Dockerfile.display
    container_name: kiosk-452-display
    ports:
      - "5900:5900"  # VNC port
    volumes:
      - ../assets:/app/assets
    environment:
      - DISPLAY=:0
      - VNC_PASSWORD=raspberry
      - KIOSK_URL=http://kiosk-frontend
    depends_on:
      - kiosk-frontend
      - kiosk-backend
    restart: unless-stopped
    networks:
      - kiosk-network

volumes:
  ollama_data:

networks:
  kiosk-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16
