version: '3.8'

services:
  kiosk-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kiosk-452-dev
    ports:
      - "5900:5900"  # VNC port
    volumes:
      - ../kiosk:/app/kiosk
      - ../voice:/app/voice
      - ../sensors:/app/sensors
      - ../assets:/app/assets
      - ../config:/app/config
    environment:
      - DISPLAY=:0
      - VNC_PASSWORD=raspberry
    restart: unless-stopped
    privileged: false
    networks:
      - kiosk-network

networks:
  kiosk-network:
    driver: bridge
